[package]
name = "edgeware-runtime-wasm"
version = "0.1.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]

[lib]
name = "edgeware_runtime"
crate-type = ["cdylib"]

[dependencies]
edgeware-runtime = { path = "..", default-features = false }

[features]
default = ["core"]
core = [
	"edgeware-runtime/core",
]
std = [
	"edgeware-runtime/std",
]

[profile.release]
panic = "abort"
lto = true

[workspace]
members = []
