[package]
name = "edgeware-runtime"
version = "0.1.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"

[dependencies]
edge-voting = { path = "../../modules/edge-voting", default-features = false }

[features]
default = ["std"]
core = [
]
std = [
	"edge-voting/std",
]
